version: "3.9"

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    volumes:
      - kong_db_data:/var/lib/postgresql/data
    networks:
      - kong-net

  kong-migrations:
    image: kong:3.6
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: 12345
      KONG_PG_USER: postgres
      KONG_PG_DATABASE: kong
    networks:
      - kong-net

  kong:
    image: kong:3.6
    container_name: kong
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: 12345
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - kong-net

  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "1337:1337"
    networks:
      - kong-net
    depends_on:
      - kong

volumes:
  kong_db_data:

networks:
  kong-net:
    driver: bridge
