package medicalrecordhandler

import (
	"hospital-service/internal/repositories/patientrepo"
	"hospital-service/internal/services/medicalrecordservice"
	"hospital-service/internal/services/subscriptionservice"
	"hospital-service/internal/utils"
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
)

type AIDiagnosisHandler struct {
	service            *medicalrecordservice.AIDiagnosisService
	subscriptionService *subscriptionservice.SubscriptionService
	patientRepo        *patientrepo.PatientRepo
}

// NewAIDiagnosisHandler khởi tạo handler
func NewAIDiagnosisHandler(service *medicalrecordservice.AIDiagnosisService, subscriptionService *subscriptionservice.SubscriptionService, patientRepo *patientrepo.PatientRepo) *AIDiagnosisHandler {
	return &AIDiagnosisHandler{
		service:             service,
		subscriptionService: subscriptionService,
		patientRepo:         patientRepo,
	}
}

// ---------------- Create AI Diagnosis ----------------
// @Summary Create a new AI diagnosis
// @Description Create an AI diagnosis record (generated by AI model) with optional image upload
// @Tags AI Diagnoses
// @Accept multipart/form-data
// @Produce json
// @Param patient_id formData string true "Patient ID"
// @Param record_id formData string true "Record ID"
// @Param disease_code formData string true "Disease Code"
// @Param confidence formData number true "AI Confidence (0–1)"
// @Param eye_type formData string false "Eye Type (left/right)"
// @Param notes formData string false "Additional Notes"
// @Param main_image formData file false "Main image file"
// @Success 201 {object} medicalrecordservice.AIDiagnosisResponse
// @Failure 400 {object} map[string]string
// @Failure 500 {object} map[string]string
// @Router /ai-diagnoses [post]
func (h *AIDiagnosisHandler) Create(c *gin.Context) {
	patientID := c.PostForm("patient_id")
	recordID := c.PostForm("record_id")
	diseaseCode := c.PostForm("disease_code")
	confidenceStr := c.PostForm("confidence")
	eyeType := c.PostForm("eye_type")
	notes := c.PostForm("notes")

	if patientID == "" || diseaseCode == "" || confidenceStr == "" {
		c.JSON(http.StatusBadRequest, utils.ErrorResponse(http.StatusBadRequest, "Missing required fields"))
		return
	}

	// Lấy patient để lấy user_id
	patient, err := h.patientRepo.FindByID(patientID)
	if err != nil {
		c.JSON(http.StatusBadRequest, utils.ErrorResponse(http.StatusBadRequest, "Patient not found"))
		return
	}

	if patient.UserID == "" {
		c.JSON(http.StatusBadRequest, utils.ErrorResponse(http.StatusBadRequest, "Patient does not have user_id"))
		return
	}

	// Check subscription limit trước khi tạo AI diagnosis
	checkResult, err := h.subscriptionService.CheckAILimit(patient.UserID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, utils.ErrorResponse(http.StatusInternalServerError, err.Error()))
		return
	}

	if !checkResult.CanUse {
		c.JSON(http.StatusForbidden, utils.ErrorResponse(http.StatusForbidden, "Subscription limit exceeded. Please upgrade your plan."))
		return
	}

	// parse confidence (float)
	confidence, err := strconv.ParseFloat(confidenceStr, 64)
	if err != nil {
		c.JSON(http.StatusBadRequest, utils.ErrorResponse(http.StatusBadRequest, "Invalid confidence value"))
		return
	}

	// lấy file ảnh chính (nếu có)
	var mainImageFile interface{}
	fileHeader, err := c.FormFile("main_image")
	if err == nil {
		mainImageFile = fileHeader
	}

	req := medicalrecordservice.CreateAIDiagnosisRequest{
		PatientID:   patientID,
		RecordID:    recordID,
		DiseaseCode: diseaseCode,
		Confidence:  confidence,
	}
	if eyeType != "" {
		req.EyeType = &eyeType
	}
	if notes != "" {
		req.Notes = &notes
	}

	res, err := h.service.Create(req, mainImageFile)
	if err != nil {
		c.JSON(http.StatusInternalServerError, utils.ErrorResponse(http.StatusInternalServerError, err.Error()))
		return
	}

	// Update usage sau khi tạo thành công
	err = h.subscriptionService.UpdateUsage(patient.UserID, true) // true = AI usage
	if err != nil {
		// Log error nhưng không fail request vì đã tạo thành công
		c.JSON(http.StatusCreated, utils.SuccessResponse(http.StatusCreated, "AI diagnosis created successfully but failed to update usage", res))
		return
	}

	c.JSON(http.StatusCreated, utils.SuccessResponse(http.StatusCreated, "AI diagnosis created successfully", res))
}

// ---------------- Get All Pending Diagnoses ----------------
// @Summary Get all AI diagnoses with status PENDING
// @Description Retrieve all AI diagnosis records that are awaiting doctor verification
// @Tags AI Diagnoses
// @Produce json
// @Success 200 {array} medicalrecordservice.AIDiagnosisResponse
// @Failure 500 {object} map[string]string
// @Router /ai-diagnoses [get]
func (h *AIDiagnosisHandler) FindAllPending(c *gin.Context) {
	diagnoses, err := h.service.FindAll()
	if err != nil {
		c.JSON(http.StatusInternalServerError, utils.ErrorResponse(http.StatusInternalServerError, err.Error()))
		return
	}

	c.JSON(http.StatusOK, utils.SuccessResponse(http.StatusOK, "Pending diagnoses retrieved successfully", diagnoses))
}

// ---------------- Get By Patient ID ----------------
// @Summary Get AI diagnoses by patient ID
// @Description Retrieve AI diagnosis records for a specific patient (all statuses)
// @Tags AI Diagnoses
// @Produce json
// @Param patient_id path string true "Patient ID"
// @Success 200 {array} medicalrecord.AIDiagnosis
// @Failure 400 {object} map[string]string
// @Failure 500 {object} map[string]string
// @Router /ai-diagnoses/patient/{patient_id} [get]
func (h *AIDiagnosisHandler) FindByPatientID(c *gin.Context) {
	patientID := c.Param("patient_id")
	if patientID == "" {
		c.JSON(http.StatusBadRequest, utils.ErrorResponse(http.StatusBadRequest, "patient_id is required"))
		return
	}

	diagnoses, err := h.service.FindByPatientID(patientID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, utils.ErrorResponse(http.StatusInternalServerError, err.Error()))
		return
	}

	c.JSON(http.StatusOK, utils.SuccessResponse(http.StatusOK, "Diagnoses for patient retrieved successfully", diagnoses))
}

// ---------------- Verify Diagnosis ----------------
// @Summary Verify an AI diagnosis
// @Description Doctor verifies AI diagnosis and updates status, notes, and signature
// @Tags AI Diagnoses
// @Accept multipart/form-data
// @Produce json
// @Param id path string true "Diagnosis ID"
// @Param doctor_id formData string true "Doctor ID"
// @Param status formData string true "Status (VERIFIED/REJECTED)"
// @Param notes formData string false "Doctor Notes"
// @Param signature formData file false "Doctor Signature Image"
// @Success 200 {object} map[string]string
// @Failure 400 {object} map[string]string
// @Failure 500 {object} map[string]string
// @Router /ai-diagnoses/{id}/verify [put]
func (h *AIDiagnosisHandler) Verify(c *gin.Context) {
	id := c.Param("id")
	doctorID := c.PostForm("doctor_id")
	status := c.PostForm("status")
	notes := c.PostForm("notes")

	if doctorID == "" || status == "" {
		c.JSON(http.StatusBadRequest, utils.ErrorResponse(http.StatusBadRequest, "Missing required fields: doctor_id, status"))
		return
	}

	// Lấy file signature (nếu có)
	var signatureFile interface{}
	fileHeader, err := c.FormFile("signature")
	if err == nil {
		signatureFile = fileHeader
	}

	err = h.service.Verify(id, doctorID, status, notes, signatureFile)
	if err != nil {
		c.JSON(http.StatusInternalServerError, utils.ErrorResponse(http.StatusInternalServerError, err.Error()))
		return
	}

	c.JSON(http.StatusOK, utils.SuccessResponse(http.StatusOK, "Diagnosis verified successfully", nil))
}
