package medicalrecordhandler

import (
	"hospital-service/internal/services/medicalrecordservice"
	"hospital-service/internal/utils"
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
)

type AIDiagnosisHandler struct {
	service *medicalrecordservice.AIDiagnosisService
}

// NewAIDiagnosisHandler khởi tạo handler
func NewAIDiagnosisHandler(service *medicalrecordservice.AIDiagnosisService) *AIDiagnosisHandler {
	return &AIDiagnosisHandler{service: service}
}

// ---------------- Create AI Diagnosis ----------------
// @Summary Create a new AI diagnosis
// @Description Create an AI diagnosis record (generated by AI model) with optional image upload
// @Tags AI Diagnoses
// @Accept multipart/form-data
// @Produce json
// @Param patient_id formData string true "Patient ID"
// @Param record_id formData string true "Record ID"
// @Param disease_code formData string true "Disease Code"
// @Param confidence formData number true "AI Confidence (0–1)"
// @Param eye_type formData string false "Eye Type (left/right)"
// @Param notes formData string false "Additional Notes"
// @Param main_image formData file false "Main image file"
// @Success 201 {object} medicalrecordservice.AIDiagnosisResponse
// @Failure 400 {object} map[string]string
// @Failure 500 {object} map[string]string
// @Router /ai-diagnoses [post]
func (h *AIDiagnosisHandler) Create(c *gin.Context) {
	patientID := c.PostForm("patient_id")
	recordID := c.PostForm("record_id")
	diseaseCode := c.PostForm("disease_code")
	confidenceStr := c.PostForm("confidence")
	eyeType := c.PostForm("eye_type")
	notes := c.PostForm("notes")

	if patientID == "" || diseaseCode == "" || confidenceStr == "" {
		c.JSON(http.StatusBadRequest, utils.ErrorResponse(http.StatusBadRequest, "Missing required fields"))
		return
	}

	// parse confidence (float)
	confidence, err := strconv.ParseFloat(confidenceStr, 64)
	if err != nil {
		c.JSON(http.StatusBadRequest, utils.ErrorResponse(http.StatusBadRequest, "Invalid confidence value"))
		return
	}

	// lấy file ảnh chính (nếu có)
	var mainImageFile interface{}
	fileHeader, err := c.FormFile("main_image")
	if err == nil {
		mainImageFile = fileHeader
	}

	req := medicalrecordservice.CreateAIDiagnosisRequest{
		PatientID:   patientID,
		RecordID:    recordID,
		DiseaseCode: diseaseCode,
		Confidence:  confidence,
	}
	if eyeType != "" {
		req.EyeType = &eyeType
	}
	if notes != "" {
		req.Notes = &notes
	}

	res, err := h.service.Create(req, mainImageFile)
	if err != nil {
		c.JSON(http.StatusInternalServerError, utils.ErrorResponse(http.StatusInternalServerError, err.Error()))
		return
	}

	c.JSON(http.StatusCreated, utils.SuccessResponse(http.StatusCreated, "AI diagnosis created successfully", res))
}

// ---------------- Get All Pending Diagnoses ----------------
// @Summary Get all AI diagnoses with status PENDING
// @Description Retrieve all AI diagnosis records that are awaiting doctor verification
// @Tags AI Diagnoses
// @Produce json
// @Success 200 {array} medicalrecordservice.AIDiagnosisResponse
// @Failure 500 {object} map[string]string
// @Router /ai-diagnoses [get]
func (h *AIDiagnosisHandler) FindAllPending(c *gin.Context) {
	diagnoses, err := h.service.FindAll()
	if err != nil {
		c.JSON(http.StatusInternalServerError, utils.ErrorResponse(http.StatusInternalServerError, err.Error()))
		return
	}

	c.JSON(http.StatusOK, utils.SuccessResponse(http.StatusOK, "Pending diagnoses retrieved successfully", diagnoses))
}

// ---------------- Get By Patient ID ----------------
// @Summary Get AI diagnoses by patient ID
// @Description Retrieve AI diagnosis records for a specific patient (all statuses)
// @Tags AI Diagnoses
// @Produce json
// @Param patient_id path string true "Patient ID"
// @Success 200 {array} medicalrecord.AIDiagnosis
// @Failure 400 {object} map[string]string
// @Failure 500 {object} map[string]string
// @Router /ai-diagnoses/patient/{patient_id} [get]
func (h *AIDiagnosisHandler) FindByPatientID(c *gin.Context) {
	patientID := c.Param("patient_id")
	if patientID == "" {
		c.JSON(http.StatusBadRequest, utils.ErrorResponse(http.StatusBadRequest, "patient_id is required"))
		return
	}

	diagnoses, err := h.service.FindByPatientID(patientID)
	if err != nil {
		c.JSON(http.StatusInternalServerError, utils.ErrorResponse(http.StatusInternalServerError, err.Error()))
		return
	}

	c.JSON(http.StatusOK, utils.SuccessResponse(http.StatusOK, "Diagnoses for patient retrieved successfully", diagnoses))
}

// ---------------- Verify Diagnosis ----------------
// @Summary Verify an AI diagnosis
// @Description Doctor verifies AI diagnosis and updates status, notes, and signature
// @Tags AI Diagnoses
// @Accept json
// @Produce json
// @Param id path string true "Diagnosis ID"
// @Param body body map[string]string true "Verification data (doctor_id, status, notes, signature)"
// @Success 200 {object} map[string]string
// @Failure 400 {object} map[string]string
// @Failure 500 {object} map[string]string
// @Router /ai-diagnoses/{id}/verify [put]
func (h *AIDiagnosisHandler) Verify(c *gin.Context) {
	id := c.Param("id")

	var req struct {
		DoctorID  string `json:"doctor_id" binding:"required"`
		Status    string `json:"status" binding:"required"`
		Notes     string `json:"notes"`
		Signature string `json:"signature"`
	}

	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, utils.ErrorResponse(http.StatusBadRequest, "Invalid request: "+err.Error()))
		return
	}

	err := h.service.Verify(id, req.DoctorID, req.Status, req.Notes, req.Signature)
	if err != nil {
		c.JSON(http.StatusInternalServerError, utils.ErrorResponse(http.StatusInternalServerError, err.Error()))
		return
	}

	c.JSON(http.StatusOK, utils.SuccessResponse(http.StatusOK, "Diagnosis verified successfully", nil))
}
